# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# Minecraft Properties
minecraft_version=1.19.2
minecraft_version_range=[1.19.2]
forge_version=43.5.0
forge_version_range=[43,)
forge_loader_range=[43,)

# Mod Properties
mod_version=1.2.3
mod_id=immersivethunder
mod_name=ImmersiveThunder
mod_author=ImmersiveThunder Team
mod_description=A forge mod that adds realistic and dynamic thunder sounds to Minecraft based on the player's distance from the lightning strike.

maven_group=com.bludos.forge
archives_base_name=ImmersiveThunder-forge-1.19.2

# Mappings
parchment_version=2022.08.14
